# This rule is not used by the project bmc-secret-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to config.metal.ironcore.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bmc-secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretbackendconfig-viewer-role
rules:
- apiGroups:
  - config.metal.ironcore.dev
  resources:
  - secretbackendconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.metal.ironcore.dev
  resources:
  - secretbackendconfigs/status
  verbs:
  - get
